### ISSUE TITLE
create collection and flow

### ISSUE THREAD

**Issue by xu4wang** [br41nslug/directus-extension-ai-pack#1]
Hi @br41nslug 

Thanks for the interesting extension!

Do I need to manually create collection or flow after the installation? I was following the `Manual Installation` section in the README file. but was not able to find collection and flow after restart directus instance.

BR,Austin

**Comment by xu4wang** [comment]
checking the screen captures in the readme, I realized creating collection and flow is required.  
Would you please share me the script for retrieving the response from operation and updating the collection?

**Comment by br41nslug** [comment]
Sure thing @xu4wang they're pretty basic so didnt give a second thought to including those:
**DALL-E and Stable Diffusion Demo Script Operation**\
where `result` is the field im using in my data-model.
```js
module.exports = async function(data) {
	const { payload } = data['$trigger'];
    payload.result = data['$last'].id;
	return payload;
}
```
**Davinci Demo Script Operation**
```js
module.exports = async function(data) {
	const { payload } = data['$trigger'];
    payload.response = data['$last'].response;
	return payload;
}
```
