### ISSUE TITLE
Feature Request - Ability to specify the model in ChatGPT operation

### ISSUE THREAD

**Issue by davidpp** [br41nslug/directus-extension-ai-pack#10]
Since GPT-4 is now available, add a dropdown (or input field to override) to specify the model to be used instead of hardcoding the value.

Current available values: gpt-4, gpt-3.5-turbo.

**Comment by br41nslug** [comment]
Feel free to create a PR to implement it 😄

**Comment by BlackDahlia313** [comment]
> Feel free to create a PR to implement it 😄

ok 🤓

**Comment by BlackDahlia313** [comment]
Done. Added a dropdown with all available models as well as updated openai from v3 to the latest v4. 

I'll get a PR up after dinner

**Comment by BlackDahlia313** [comment]
https://github.com/br41nslug/directus-extension-ai-pack/pull/11

**Comment by BlackDahlia313** [comment]
@davidpp This is now merged! Give it a try and let's get this issue closed! :)

**Comment by br41nslug** [comment]
Added and released in version 2.0.0! Big thanks to @BlackDahlia313 🚀
