### ISSUE TITLE
Stable Diffusion  "code": "SERVICE_UNAVAILABLE"

### ISSUE THREAD

**Issue by stephan-schmidt** [br41nslug/directus-extension-ai-pack#4]
Really, Really love these extensions! Awesome work. 
Question for the Stable Diffusion API, The payload in the flow sends me this back: 

```
{
  "message": "Couldn't save file 9d25ab50-d1bf-4fa5-8d9d-dbe44a4b8c44.png",
  "code": "SERVICE_UNAVAILABLE",
  "extensions": {
    "service": "files"
  },
  "status": 503
}
```
Do I have to permit some settings? 
The Dalle-E has no issues!

**Comment by br41nslug** [comment]
Can't say i've had to set specific permissions for this but my test scenario is pretty limited. Do you have any custom permissions on `directus_files` that could be interfering here?

**Comment by stephan-schmidt** [comment]
> Can't say i've had to set specific permissions for this but my test scenario is pretty limited. Do you have any custom permissions on `directus_files` that could be interfering here?

The approved pull #6  by @Sothos solved it, had the same issue with the local storage but using a Digital Ocean Space. 
Thanks again for building this in the first place and the pull!

**Comment by br41nslug** [comment]
Awesome thanks for the update 😄 will close this as resolved then
