### ISSUE TITLE
save button taking too long, possible to update the user regarding the progress?

### ISSUE THREAD

**Issue by xu4wang** [br41nslug/directus-extension-ai-pack#5]
This is a general question regarding Directus UX, not only for this wonderful AI extension.

When I click the save button on the upper right corner. It starts to loading ( while the flow is being executed on the background).
Some times it takes quite a long time to finish.

It would be easier for the user to be updated regarding the progress.  I feel only one "loading button" is not enough.  It will be better if a notification dialog can be shown during the flow execution.

**Comment by br41nslug** [comment]
that is not something i can change in the context of this extension as thats more how Directus Flows work in general than the function of these operations 😬
